Updates the error message for installing tools (#67)
* Updates the error message for installing tools

Adds a better error output for this step, changing from:
```
Installing the following tools:
- servicelogger v0.1.1
- aws 2.15.34
- oc 4.15.3
- butane v0.20.0
Error: failed to locate latest archive matching system spec: unexpected number of assets found matching system spec: expected at least 1, got 0```

to

```
Installing the following tools:
- servicelogger v0.1.1
- aws 2.15.34
- oc 4.15.3
- butane v0.20.0
Unable to install the latest version of osdctl: Error: failed to locate latest archive matching system spec: unexpected number of assets found matching system spec: expected at least 1, got 0
```

This way you can at least see as the end user if it's the same package that's failing to install.

* lint